// Wars Service Worker — minimal offline shell (P0).
// Caches app shell for instant reload on flaky 3G.
// Base-path aware: works at site root (standalone) AND under /wars-app/ (GitHub Pages).
// Static-export note: on GH Pages there is no /manifest.webmanifest file (it was
// generated by the server at runtime), so the install list tolerates misses.
// No runtime caching of API or images yet (P2 concern).

const BASE = new URL(self.registration.scope).pathname;
const CACHE = "wars-shell-v1";
const SHELL = [
  `${BASE}`,
  `${BASE}manifest.webmanifest`,
  `${BASE}icons/icon-192.svg`,
];

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(CACHE).then((cache) =>
      Promise.allSettled(SHELL.map((u) => cache.add(u))),
    ),
  );
  self.skipWaiting();
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))),
    ),
  );
  self.clients.claim();
});

self.addEventListener("fetch", (event) => {
  const { request } = event;
  // Only handle GET; skip cross-origin (API, TMDb images).
  if (request.method !== "GET" || new URL(request.url).origin !== self.location.origin) {
    return;
  }
  event.respondWith(
    caches.match(request).then((cached) => {
      if (cached) return cached;
      return fetch(request)
        .then((res) => {
          // Cache successful same-origin GETs (navigations + assets).
          if (res.ok) {
            const clone = res.clone();
            caches.open(CACHE).then((c) => c.put(request, clone)).catch(() => {});
          }
          return res;
        })
        .catch(() => {
          // Offline fallback: serve cached scope root for navigations.
          if (request.mode === "navigate") {
            return caches.match(`${BASE}`);
          }
          throw new Error("offline");
        });
    }),
  );
});